In [5]:
import numpy as np
import tensorflow as tf

physical_devices = tf.config.experimental.list_physical_devices("GPU")
print("Number of GPU: ", len(physical_devices))
print(physical_devices)

if len(physical_devices) != 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)


model = tf.keras.models.load_model("data/output.h5")

Number of GPU:  1
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [34]:
test = np.load("data/x1.npy")[0]
y = np.load("data/y1.npy")

results = []

for i in range(len(y)):
    result = model.predict(test.reshape(-1, 20, 1), verbose=1)
    test = test[1:]
    test = np.append(test, result)
    results.append(result[0])

np.array(results).shape, y.shape

1/1 [==============================] - 0s 22ms/step


((980, 1), (980, 1))

In [36]:
results

[array([0.75022215], dtype=float32),
 array([0.74027145], dtype=float32),
 array([0.725779], dtype=float32),
 array([0.71047807], dtype=float32),
 array([0.6962284], dtype=float32),
 array([0.68360615], dtype=float32),
 array([0.67257977], dtype=float32),
 array([0.66288906], dtype=float32),
 array([0.6542162], dtype=float32),
 array([0.6462754], dtype=float32),
 array([0.6388363], dtype=float32),
 array([0.63172305], dtype=float32),
 array([0.6248238], dtype=float32),
 array([0.6180603], dtype=float32),
 array([0.61140573], dtype=float32),
 array([0.60486215], dtype=float32),
 array([0.5984401], dtype=float32),
 array([0.59214175], dtype=float32),
 array([0.58599997], dtype=float32),
 array([0.58001304], dtype=float32),
 array([0.57419825], dtype=float32),
 array([0.56854266], dtype=float32),
 array([0.56306094], dtype=float32),
 array([0.5577482], dtype=float32),
 array([0.552598], dtype=float32),
 array([0.5476031], dtype=float32),
 array([0.54275566], dtype=float32),
 array([0.5380

In [35]:
np.save("data/results", results)